import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/ui/components/Footer/Footer";
import { Navigation } from "@/ui/components/Navigation/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
